//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoAkademi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egitmen()
        {
            this.Kurslar = new HashSet<Kurslar>();
        }
    
        public int egitmenId { get; set; }
        public string egitmenAd { get; set; }
        public string egitmenSoyad { get; set; }
        public string egitmenBrans { get; set; }
        public string egitmenOzgecmis { get; set; }
        public string egitmenFotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurslar> Kurslar { get; set; }
    }
}
