//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoAkademi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurslar
    {
        public int kursId { get; set; }
        public string kursAd { get; set; }
        public decimal kursFiyat { get; set; }
        public string kursIcerik { get; set; }
        public int kursKategoriId { get; set; }
        public int kursEgitmenId { get; set; }
    
        public virtual Egitmen Egitmen { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
