//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoAkademi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public int uyeId { get; set; }
        public string uyeAd { get; set; }
        public string uyeSoyad { get; set; }
        public string uyeTel { get; set; }
        public string uyeMail { get; set; }
        public string uyeParola { get; set; }
        public string uyeYetki { get; set; }
    }
}
